src/groups/urls.py
from django.urls import path

from groups import views

app_name = 'groups'

urlpatterns = [
    path('create/', views.create_group, name='create'),
    path('edit/<int:pk>/', views.edit_group, name='edit'),
    path('delete/<int:pk>/', views.delete_group, name='delete'),
    path('list/', views.groups, name='list'),
]

src/groups/models.py
from django.db import models


class Group(models.Model):

    group_name = models.CharField(max_length=64)
    faculty = models.CharField(max_length=64)
    university_name = models.CharField(max_length=64)
    curator = models.ForeignKey('teachers.Teacher',
                                on_delete=models.SET_NULL, null=True)
    headman = models.ForeignKey('students.Student',
                                on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return 'GroupName: {}. Faculty: {}. University: {}. Curator: {}. Headman: {}'.\
            format(self.group_name, self.faculty, self.university_name, self.curator.full_name, self.headman.full_name)

src/groups/forms.py
from django import forms

from groups.models import Group


class GroupCreateForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = (
            'group_name',
            'faculty',
            'university_name',
            'curator',
            'headman',
        )

src/groups/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from groups.models import Group


def groups(request):
    groups = Group.objects.all().select_related('curator', 'headman')
    return render(request, 'groups-list.html', context={'groups': groups})


def create_group(request):
    from groups.forms import GroupCreateForm
    if request.method == 'POST':
        form = GroupCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('groups:list'))
    else:
        form = GroupCreateForm()

    context = {'create_form': form}

    return render(request, 'create.html', context=context)


def edit_group(request, pk):
    from groups.forms import GroupCreateForm
    group = get_object_or_404(Group, id=pk)
    if request.method == 'POST':
        form = GroupCreateForm(request.POST, instance=group)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('groups:list'))
    else:
        form = GroupCreateForm(instance=group)

    context = {'form': form}

    return render(request, 'edit.html', context=context)


def delete_group(request, pk):
    group = get_object_or_404(Group, id=pk)
    group.delete()
    return HttpResponseRedirect(reverse('groups:list'))

src/groups/templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

Create group

<form method="post">
    {% csrf_token %}
    {{ create_form.as_p }}
    <button type="submit">GO</button>
</form>


</body>
</html>

src/groups/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

Edit group

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">GO</button>
</form>


</body>
</html>

src/groups/templates/groups-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<a href="{% url 'index' %}">Index</a>
<a href="{% url 'groups:create' %}">Create group</a> <br>

<table>
    <tr>
    <th> Group Name </th>
    <th> faculty </th>
    <th> university_name </th>
    <th> curator </th>
    <th> headman </th>
        </tr>
{% for group in groups %}
    <tr>
    <td>   <a href="{% url 'groups:edit' pk=group.id %}"> {{ group.id }} </a> </td>
    <td>   {{ group.faculty }}  </td>
    <td> {{ group.university_name }} </td>
    <td> <a href="{% url 'teachers:edit' pk=group.curator.id %}"> {{ group.curator.full_name }} </a></td>
    <td> <a href="{% url 'students:edit' pk=group.headman.id %}"> {{ group.headman.full_name }} </a></td>
    <td><a href="{% url 'groups:delete' pk=group.id %}">Delete</a><br></td>
    </tr>
{% endfor %}

</table>

</body>
</html>