src/teachers/urls.py
from django.urls import path

from teachers import views


app_name = 'teachers'

urlpatterns = [
    path('create/', views.create_teacher, name='create'),
    path('edit/<int:pk>/', views.edit_teacher, name='edit'),
    path('delete/<int:pk>/', views.delete_teacher, name='delete'),
    path('list/', views.teachers, name='list'),
]

src/teachers/models.py
from django.db import models


class Teacher(models.Model):

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    age = models.PositiveSmallIntegerField()
    education = models.CharField(max_length=64)

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return 'FirstName: {}. LastName: {}. Age: {}. Education: {}'.\
            format(self.first_name, self.last_name, self.age, self.education)

src/teachers/forms.py
from django import forms

from teachers.models import Teacher


class TeacherCreateForm(forms.ModelForm):

    class Meta:
        model = Teacher
        fields = (
            'first_name',
            'last_name',
            'age',
            'education',
        )

src/teachers/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from teachers.models import Teacher


def teachers(request):
    teachers = Teacher.objects.all()
    return render(request, 'teachers-list.html', context={'teachers': teachers})


def create_teacher(request):
    from teachers.forms import TeacherCreateForm
    if request.method == 'POST':
        form = TeacherCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('teachers:list'))
    else:
        form = TeacherCreateForm()

    context = {'create_form': form}

    return render(request, 'create.html', context=context)


def edit_teacher(request, pk):
    from teachers.forms import TeacherCreateForm
    student = get_object_or_404(Teacher, id=pk)
    if request.method == 'POST':
        form = TeacherCreateForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('teachers:list'))
    else:
        form = TeacherCreateForm(instance=student)

    context = {'form': form}

    return render(request, 'edit.html', context=context)


def delete_teacher(request, pk):
    teacher = get_object_or_404(Teacher, id=pk)
    teacher.delete()
    return HttpResponseRedirect(reverse('teachers:list'))

src/teachers/templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

Create teacher

<form method="post">
    {% csrf_token %}
    {{ create_form.as_p }}
    <button type="submit">GO</button>
</form>

</body>
</html>

src/teachers/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

Edit teacher

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">GO</button>
</form>


</body>
</html>

src/teachers/templates/teachers-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<a href="{% url 'index' %}">Index</a>
<a href="{% url 'teachers:create' %}">Create teacher</a> <br>

{% for teacher in teachers %}
    <a href="{% url 'teachers:edit' pk=teacher.id %}"> {{ teacher.id }} </a>
{{ teacher }}  <a href="{% url 'teachers:delete' pk=teacher.id %}">Delete</a><br>
{% endfor %}


</body>
</html>