src/students/urls.py
from django.urls import path

from students import views

app_name = 'students'

urlpatterns = [
    path('create/', views.create_student, name='create'),
    path('edit/<int:pk>/', views.edit_student, name='edit'),
    path('delete/<int:pk>/', views.delete_student, name='delete'),
    path('list/', views.students, name='list'),
    path('contact-us/', views.contact_us, name='contact'),
]

src/students/models.py
from django.db import models


class Student(models.Model):

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    age = models.PositiveSmallIntegerField()
    phone = models.CharField(max_length=24)

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def info(self):
        return f'{self.id} {self.first_name} {self.last_name} {self.age}'

    def inc_age(self):
        self.age += 1
        self.save()

    def __str__(self):
        return 'FirstName: {}. LastName: {}. Age: {}'.format(self.first_name, self.last_name, self.age)  # noqa

src/students/forms.py
from django import forms
from django.core.exceptions import ValidationError

from students.models import Student


class StudentCreateForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = (
            'first_name',
            'last_name',
            'age',
            'phone',
        )

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if not str(phone).isdigit():
            raise ValidationError(message='Field phone not a digit!')
        else:
            return phone


class ContactUs(forms.Form):
    title = forms.CharField(max_length=32)
    message = forms.CharField(max_length=256)
    email_from = forms.EmailField()

src/students/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from students.forms import ContactUs
from students.models import Student
from students.tasks import send_mail_async

from students_tracker.helper import check_param_value_is_valid, create_random_student


def generate_student(request):
    student = create_random_student()
    return HttpResponse(student)


def generate_students(request):
    count = 10
    result = []
    if request.GET.get('count'):
        if check_param_value_is_valid(request.GET.get('count')):
            count = request.GET.get('count')
        result = [str(create_random_student()) + '\n' for _ in range(int(count))]
    return HttpResponse(result)


def students(request):
    students = Student.objects.all()
    return render(request, 'students-list.html', context={'students': students})


def create_student(request):
    from students.forms import StudentCreateForm
    if request.method == 'POST':
        form = StudentCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('students:list'))
    else:
        form = StudentCreateForm()

    context = {'create_form': form}

    return render(request, 'create.html', context=context)


def edit_student(request, pk):
    from students.forms import StudentCreateForm
    student = get_object_or_404(Student, id=pk)
    if request.method == 'POST':
        form = StudentCreateForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('students:list'))
    else:
        form = StudentCreateForm(instance=student)

    context = {'form': form}

    return render(request, 'edit.html', context=context)


def delete_student(request, pk):
    student = get_object_or_404(Student, id=pk)
    student.delete()
    return HttpResponseRedirect(reverse('students:list'))


def contact_us(request):
    if request.method == 'POST':
        form = ContactUs(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            result = {'title': cleaned_data.get('title'),
                      'message': cleaned_data.get('message'),
                      'email_from': cleaned_data.get('email_from')}
            send_mail_async.apply_async(args=[result])
        return HttpResponseRedirect(reverse('index'))
    form = ContactUs()
    context = {'form': form}
    return render(request, 'contact-us.html', context=context)

src/students/templates/contact-us.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

Contact us

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">GO</button>
</form>

</body>
</html>

src/students/templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

Create student

<form method="post">
    {% csrf_token %}
    {{ create_form.as_p }}
    <button type="submit">GO</button>
</form>

</body>
</html>

src/students/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

Edit student

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">GO</button>
</form>


</body>
</html>

src/students/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<a href="{% url 'students:create' %}">Create Students</a>
<a href="{% url 'students:list' %}">List Students</a> <br>
<a href="{% url 'teachers:create' %}">Create teacher</a>
<a href="{% url 'teachers:list' %}">List teachers</a> <br>
<a href="{% url 'groups:create' %}">Create group</a>
<a href="{% url 'groups:list' %}">List groups</a> <br>
<br>
<br>
<a href="{% url 'students:contact' %}">Contacts Us</a> <br>

</body>
</html>

src/students/templates/students-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<a href="{% url 'index' %}">Index</a>
<a href="{% url 'students:create' %}">Create student</a> <br>

{% for student in students %}
    <a href="{% url 'students:edit' pk=student.id %}"> {{ student.id }} </a>
{{ student.full_name }}  <a href="{% url 'students:delete' pk=student.id %}">Delete</a><br>
{% endfor %}


</body>
</html>